version: '3.1'

services:
  netmaulserver:
    build: .
    container_name: "netmaulserver"
    command: ["./netm4ul","start", "server", "-v"]
    ports:
      - 8080:8080

  netmaulclient:
    container_name: "netmaulclient"
    build: .
    command: ["./netm4ul","start", "client", "-v"]
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
#  mongodb:
#    image: mongo:latest
#    container_name: "mongodb"
#    environment:
#      MONGO_DATA_DIR: /data/db
#      MONGO_LOG_DIR: /dev/null
#      # MONGODB_USER: user
#      # MONGODB_PASS: pass
#    volumes:
#      - ./data/db:/data/db
#    ports:
#      - 27017:27017
#    command: mongod --smallfiles --logpath=/dev/null # --quiet
